### ISSUE TITLE
Using Viatra Patterns (Matcher) within OCL

### ISSUE THREAD

**Issue by upohl** [upohl/eloquent#1]
We like to allow the usage of viatra patterns to improve the useability. OCL is sometime complex to specify. Patterns + corresponding matcher could ease the specification. 

http://www.eclipse.org/viatra/
http://www.eclipse.org/viatra/documentation/tutorial.php

pattern sameIpAddress(host1 : HostInstance, host2 : HostInstance, commonIp : java String)

is equal to the OCL operation

OCLContext::sameIpAddress() : Set(
   Tuple(host1 : HostInstance, host2 : HostInstance, commonIp : String
)

- specify OCL + pattern Language in one *.eloquent file  is difficult as xtext can only inherit from one grammar
Alternative:
- Specify patterns in an own file"foo.vql" 
- in the *.eloquent file than:
   include 'platform:/resource/project_name/foo.vql'

   -- calls the pattern "sameIpAddress"
   self.sameIpAddres()

   -- combine pattern matches with ocl
   self.cic.componentInstances->select(<some predicate>)->product(
     -- calls the pattern "sameIpAddress" and uses only the "host1" match
     self.sameIpAddress()->collect(match |
        match.host1
     )
   )

[1]
https://www.eclipse.org/viatra/documentation/tutorial.php#_define_additional_queries
Open question:
How to cope with Counting (7.) und Transitive Closure (8.) in [1]  during the transformation

**Comment by marcus-h** [comment]
On 2017-07-28 07:42:05 +0000, Uwe Pohlmann wrote:
> We like to allow the useage of viatra patterns to improve the useability. OCL is sometime complex to specify. Patterns + corresponding matcher could ease the specification. 
> 
This was implemented in the meantime... see commit e8a6ec3a.
Moreover, I just implemented the "explicit context object
specification"-thingy (see commit 3deba7ff and commits 1ca99f7f,
fa5f1247 for the testcases).

> Open question:
> How to cope with Counting (7.) und Transitive Closure (8.) in [1]  during the transformation
> 
The transitive closure is definitely no problem and the counting
shouldn't be a problem as well.

Hence, I'm closing this issue.
