### ISSUE TITLE
add constraint kind forbidLocation for bounds larger than 1

### ISSUE THREAD

**Issue by upohl** [upohl/eloquent#2]
If bounds becom larger than one than the required location is not sufficient anymore because the constraint is fulfilled as long as one component fulfills the requirment. In some cases you want that components should not be allocated to specific ECUs. Therefore, we like to add the constraint kind forbidLocation.  In case of bound 1 this problem does not occur.

**Comment by marcus-h** [comment]
It was implemented in the meantime (the testcases in commit
cf5db2dd5320775ee564c4614b364be6c8e059d0 demonstrate its usage).
=> Closing
(hrm reply via mail did not seem to work...)
